services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  adminer:
    image: adminer
    restart: always
    container_name: adminer-db
    ports:
      - "8081:8080"
volumes:
  pgdata:
